### PR TITLE
Make sure that the latest version can be retrieved behind proxy

### PR DESCRIPTION
**Pull request by aukevanleeuwen**
I had some problems with retrieving the latest version while being
behind a proxy. I've tried all sorts of options with ENV['http_proxy']
but was unable to make this work.
This seemed like the most logical solution, to use Chef classes
themselves.

### CODE REVIEW

**Comment by dhoer** [comment]
This is nice and clean. What version of Chef was this introduced? This cookbook currently supports Chef 11, but I can be persuaded to move to Chef 12.  There is another alternative I would like your feedback on: https://github.com/dhoer/chef-nexus3/pull/15/files.  What are the pro and cons to these approaches? Will p_port be an issue with Chef's approach?

**Comment by aukevanleeuwen** [comment]
Hey

tbh: I'm not entirely sure what version. I ran a local `kitchen verify` and that uses Chef 11 as far as I can see: this worked fine:

    chef-chromedriver 17h retrieve-latest-version-with-proxy / kitchen verify                                                                                              java-1.8.0_77
    -----> Starting Kitchen (v1.7.3)
    -----> Creating <default-centos-71>...
           Bringing machine 'default' up with 'virtualbox' provider...
           ==> default: Importing base box 'bento/centos-7.1'...
    ==> default: Matching MAC address for NAT networking...
           ==> default: Checking if box 'bento/centos-7.1' is up to date...
           ==> default: Setting the name of the VM: kitchen-chef-chromedriver-default-centos-71_default_1475133442072_58657
           ==> default: Clearing any previously set network interfaces...
           ==> default: Preparing network interfaces based on configuration...
               default: Adapter 1: nat
           ==> default: Forwarding ports...
               default: 4444 (guest) => 6444 (host) (adapter 1)
               default: 22 (guest) => 2222 (host) (adapter 1)
           ==> default: Booting VM...
           ==> default: Waiting for machine to boot. This may take a few minutes...
               default: SSH address: 127.0.0.1:2222
               default: SSH username: vagrant
               default: SSH auth method: private key
               default:
               default: Vagrant insecure key detected. Vagrant will automatically replace
               default: this with a newly generated keypair for better security.
               default:
               default: Inserting generated public key within guest...
               default: Removing insecure key from the guest if it's present...
               default: Key inserted! Disconnecting and reconnecting using new SSH key...
           ==> default: Machine booted and ready!
           ==> default: Checking for guest additions in VM...
           ==> default: Setting hostname...
           ==> default: Machine not provisioned because `--no-provision` is specified.
           [SSH] Established
           Vagrant instance <default-centos-71> created.
           Finished creating <default-centos-71> (0m37.01s).
    -----> Converging <default-centos-71>...
           Preparing files for transfer
           Preparing dna.json
           Resolving cookbook dependencies with Berkshelf 4.3.2...
           Removing non-cookbook files before transfer
           Preparing solo.rb
    -----> Installing Chef Omnibus (11.16)
           Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
           Trying wget...
           Download complete.
           el 7 x86_64
           Getting information for chef stable 11.16 for el...
           downloading https://www.getchef.com/stable/chef/metadata?v=11.16&p=el&pv=7&m=x86_64
             to file /tmp/install.sh.12424/metadata.txt
           trying wget...
           sha1	33e264eee97c225d47a4701d17aef7556d1afbd4
           sha256	278599ff185b680703e7a779db8674eeba843e9fe42a0ae06e01a9dfa9ac4d0e
           url	https://packages.chef.io/stable/el/6/chef-11.16.4-1.el6.x86_64.rpm
           version	11.16.4
           downloaded metadata file looks valid...
           downloading https://packages.chef.io/stable/el/6/chef-11.16.4-1.el6.x86_64.rpm
             to file /tmp/install.sh.12424/chef-11.16.4-1.el6.x86_64.rpm
           trying wget...
           Comparing checksum with sha256sum...
           Installing chef 11.16
           installing with rpm...
           warning: /tmp/install.sh.12424/chef-11.16.4-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
           Preparing...                          ################################# [100%]
           Updating / installing...
              1:chef-11.16.4-1.el6               ################################# [100%]
           Thank you for installing Chef!
           Transferring files to <default-centos-71>
           [2016-09-29T07:18:57+00:00] WARN:
           * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
           SSL validation of HTTPS requests is disabled. HTTPS connections are still
           encrypted, but chef is not able to detect forged replies or man in the middle
           attacks.
    
           To fix this issue add an entry like this to your configuration file:
    
           ```
             # Verify all HTTPS connections (recommended)
             ssl_verify_mode :verify_peer
    
             # OR, Verify only connections to chef-server
             verify_api_cert true
           ```
    
           To check your SSL configuration, or troubleshoot errors, you can use the
           `knife ssl check` command like so:
    
           ```
             knife ssl check -c /tmp/kitchen/solo.rb
           ```
    
           * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
           Starting Chef Client, version 11.16.4
           Compiling Cookbooks...
           Recipe: chrome::yum
             * yum_repository[google-chrome] action add[2016-09-29T07:18:58+00:00] WARN: The :add method in yum_repository has been deprecated in favor of :create. Please update your cookbook to use the :create action
    
               * template[/etc/yum.repos.d/google-chrome.repo] action create
                 - create new file /etc/yum.repos.d/google-chrome.repo
                 - update content in file /etc/yum.repos.d/google-chrome.repo from none to 11ebce
                 --- /etc/yum.repos.d/google-chrome.repo	2016-09-29 07:18:58.462211332 +0000
                 +++ /tmp/chef-rendered-template20160929-12541-dybko0	2016-09-29 07:18:58.462211332 +0000
                 @@ -1 +1,10 @@
                 +# This file was generated by Chef
                 +# Do NOT modify this file by hand.
                 +
                 +[google-chrome]
                 +name=Google Chrome Repo
                 +baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
                 +enabled=1
                 +gpgcheck=1
                 +gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
                 - change mode from '' to '0644'
                 - restore selinux security context
               * execute[yum clean metadata google-chrome] action run
                 - execute yum clean metadata --disablerepo=* --enablerepo=google-chrome
               * execute[yum-makecache-google-chrome] action run
                 - execute yum -q -y makecache --disablerepo=* --enablerepo=google-chrome
               * ruby_block[yum-cache-reload-google-chrome] action create
                 - execute the ruby block yum-cache-reload-google-chrome
               * execute[yum clean metadata google-chrome] action nothing (skipped due to action :nothing)
               * execute[yum-makecache-google-chrome] action nothing (skipped due to action :nothing)
               * ruby_block[yum-cache-reload-google-chrome] action nothing (skipped due to action :nothing)
    
             * package[google-chrome-stable] action install
               - install version 53.0.2785.116-1 of package google-chrome-stable
             Converging 32 resources
           Recipe: chromedriver_test::packages
             * package[gcc] action install
               - install version 4.8.5-4.el7 of package gcc
             * package[libffi-devel] action install
               - install version 3.0.13-16.el7 of package libffi-devel
             * package[make] action install (up to date)
           Recipe: java_se::_linux_install
             * ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz] action run
               - execute the ruby block fetch http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz
             * ruby_block[set-env-java-home] action run
               - execute the ruby block set-env-java-home
             * directory[/etc/profile.d] action create (up to date)
             * file[/etc/profile.d/jdk.sh] action create
               - create new file /etc/profile.d/jdk.sh
               - update content in file /etc/profile.d/jdk.sh from none to 26187d
               --- /etc/profile.d/jdk.sh	2016-09-29 07:24:12.482142832 +0000
               +++ /tmp/.jdk.sh20160929-12541-23wy2g	2016-09-29 07:24:12.483143332 +0000
               @@ -1 +1,2 @@
               +export JAVA_HOME=/usr/lib/jvm/java
               - change mode from '' to '0755'
               - restore selinux security context
             * ruby_block[set JAVA_HOME in /etc/environment] action run (skipped due to only_if)
             * yum_package[glibc] action install (skipped due to only_if)
             * package[tar] action install (up to date)
             * ruby_block[adding java to /usr/lib/jvm/jdk1.8.0_102] action run
               - execute the ruby block adding java to /usr/lib/jvm/jdk1.8.0_102
             * template[adding /usr/lib/jvm/.java.jinfo for debian] action create (skipped due to only_if)
             * link[/usr/lib/jvm/java] action create
               - create symlink at /usr/lib/jvm/java to /usr/lib/jvm/jdk1.8.0_102
             * ruby_block[update-alternatives] action run
               - execute the ruby block update-alternatives
             * link[/usr/lib/jvm/default-java] action create (skipped due to only_if)
           Recipe: selenium::hub
             * selenium_hub[selenium_hub] action install
             Recipe: selenium::default
               * package[unzip] action install
                 - install version 6.0-15.el7 of package unzip
               * directory[/opt/selenium/config] action create
                 - create new directory /opt/selenium/config
                 - restore selinux security context
               * directory[/opt/selenium/server] action create
                 - create new directory /opt/selenium/server
                 - restore selinux security context
               * remote_file[/opt/selenium/server/selenium-server-standalone-2.53.1.jar] action create
                 - create new file /opt/selenium/server/selenium-server-standalone-2.53.1.jar
                 - update content in file /opt/selenium/server/selenium-server-standalone-2.53.1.jar from none to 1cce6d
                 (file sizes exceed 10000000 bytes, diff output suppressed)
                 - change mode from '' to '0775'
                 - restore selinux security context
               * link[/opt/selenium/server/selenium-server-standalone.jar] action create
                 - create symlink at /opt/selenium/server/selenium-server-standalone.jar to /opt/selenium/server/selenium-server-standalone-2.53.1.jar
               - evaluate block and run any associated actions
               - Install Hub Service: selenium_hub
               * template[/opt/selenium/config/selenium_hub.json] action create
                 - create new file /opt/selenium/config/selenium_hub.json
                 - update content in file /opt/selenium/config/selenium_hub.json from none to 5ee4f3
                 --- /opt/selenium/config/selenium_hub.json	2016-09-29 07:24:38.275032832 +0000
                 +++ /tmp/chef-rendered-template20160929-12541-1plg979	2016-09-29 07:24:38.275032832 +0000
                 @@ -1 +1,16 @@
                 +{
                 +  "host": null,
                 +  "port": 4444,
                 +  "newSessionWaitTimeout": -1,
                 +  "servlets": [],
                 +  "prioritizer":  null,
                 +  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
                 +  "throwOnCapabilityNotPresent": true,
                 +  "nodePolling": 5000,
                 +  "cleanUpCycle": 5000,
                 +  "timeout": 30000,
                 +  "browserTimeout": 0,
                 +  "maxSession": 5,
                 +  "jettyMaxThreads": -1
                 +}
                 - restore selinux security context
               * user[ensure user selenium exits for selenium_hub] action create
                 - create user selenium
               * template[/etc/systemd/system/selenium_hub.service] action create
                 - create new file /etc/systemd/system/selenium_hub.service
                 - update content in file /etc/systemd/system/selenium_hub.service from none to 2bd349
                 --- /etc/systemd/system/selenium_hub.service	2016-09-29 07:24:38.410100332 +0000
                 +++ /tmp/chef-rendered-template20160929-12541-1t8hg9x	2016-09-29 07:24:38.411100832 +0000
                 @@ -1 +1,16 @@
                 +[Unit]
                 +Description=selenium_hub
                 +After=syslog.target network.target
                 +
                 +[Service]
                 +Type=simple
                 +User=selenium
                 +
                 +ExecStart=/usr/bin/java -jar "/opt/selenium/server/selenium-server-standalone.jar" -role hub -hubConfig "/opt/selenium/config/selenium_hub.json"
                 +KillMode=process
                 +Restart=on-failure
                 +RestartSec=45s
                 +
                 +[Install]
                 +WantedBy=multi-user.target
                 - change mode from '' to '0755'
                 - restore selinux security context
               * service[selenium_hub] action enable
                 - enable service service[selenium_hub]
               * service[selenium_hub] action start
                 - start service service[selenium_hub]
               * service[selenium_hub] action restart
                 - restart service service[selenium_hub]
    
           Recipe: xvfb::package
             * package[xorg-x11-fonts-100dpi] action install
               - install version 7.5-9.el7 of package xorg-x11-fonts-100dpi
             * package[xorg-x11-fonts-75dpi] action install
               - install version 7.5-9.el7 of package xorg-x11-fonts-75dpi
             * package[xorg-x11-fonts-Type1] action install
               - install version 7.5-9.el7 of package xorg-x11-fonts-Type1
             * package[xorg-x11-server-Xvfb] action install
               - install version 1.17.2-10.el7 of package xorg-x11-server-Xvfb
             * package[mesa-libGL] action install (up to date)
           Recipe: xvfb::service
             * template[/etc/systemd/system/xvfb.service] action create
               - create new file /etc/systemd/system/xvfb.service
               - update content in file /etc/systemd/system/xvfb.service from none to dc5f7e
               --- /etc/systemd/system/xvfb.service	2016-09-29 07:24:58.971375832 +0000
               +++ /tmp/chef-rendered-template20160929-12541-lhhczu	2016-09-29 07:24:58.972376332 +0000
               @@ -1 +1,10 @@
               +[Unit]
               +Description=Xvfb X Server
               +After=network.target
               +
               +[Service]
               +ExecStart=/usr/bin/Xvfb :0 -screen 0 1280x1024x24
               +
               +[Install]
               +WantedBy=multi-user.target
               - change mode from '' to '0755'
               - restore selinux security context
             * service[xvfb] action enable
               - enable service service[xvfb]
             * service[xvfb] action start
               - start service service[xvfb]
           Recipe: chrome::yum
             * yum_repository[google-chrome] action nothing (skipped due to action :nothing)
             * package[google-chrome-stable] action nothing (skipped due to action :nothing)
           Recipe: chromedriver::default
             * directory[/opt/chromedriver] action create
               - create new directory /opt/chromedriver
               - restore selinux security context
             * directory[/opt/chromedriver/chromedriver_linux64-2.24] action create
               - create new directory /opt/chromedriver/chromedriver_linux64-2.24
               - restore selinux security context
             * package[unzip] action install (up to date)
             * execute[unzip chromedriver] action nothing (skipped due to action :nothing)
             * remote_file[download chromedriver] action create
               - create new file /tmp/kitchen/cache/chromedriver_linux64-2.24.zip
               - update content in file /tmp/kitchen/cache/chromedriver_linux64-2.24.zip from none to 0c01b0
               (new content is binary, diff output suppressed)
               - restore selinux security context
             * execute[unzip chromedriver] action run
               - execute unzip -o /tmp/kitchen/cache/chromedriver_linux64-2.24.zip -d /opt/chromedriver/chromedriver_linux64-2.24 && chmod -R 0755 /opt/chromedriver/chromedriver_linux64-2.24
             * link[/usr/bin/chromedriver] action create
               - create symlink at /usr/bin/chromedriver to /opt/chromedriver/chromedriver_linux64-2.24/chromedriver
           Recipe: selenium::node
             * selenium_node[selenium_node] action install
               - Install Node Service: selenium_node
               * template[/opt/selenium/config/selenium_node.json] action create
                 - create new file /opt/selenium/config/selenium_node.json
                 - update content in file /opt/selenium/config/selenium_node.json from none to 3426a5
                 --- /opt/selenium/config/selenium_node.json	2016-09-29 07:25:00.645212332 +0000
                 +++ /tmp/chef-rendered-template20160929-12541-1500z7q	2016-09-29 07:25:00.649214332 +0000
                 @@ -1 +1,22 @@
                 +{
                 +  "capabilities": [
                 +  {
                 +    "browserName": "chrome",
                 +    "maxInstances": 5,
                 +    "version": "53.0.2785.116",
                 +    "seleniumProtocol": "WebDriver"
                 +  }
                 +],
                 +  "configuration":
                 +  {
                 +    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                 +    "maxSession": 5,
                 +    "port": 5555,
                 +    "host": "ip",
                 +    "register": true,
                 +    "registerCycle": 5000,
                 +    "hubPort": 4444,
                 +    "hubHost": "ip"
                 +  }
                 +}
                 - restore selinux security context
               * user[ensure user selenium exits for selenium_node] action create (up to date)
               * template[/etc/systemd/system/selenium_node.service] action create
                 - create new file /etc/systemd/system/selenium_node.service
                 - update content in file /etc/systemd/system/selenium_node.service from none to d0c47a
                 --- /etc/systemd/system/selenium_node.service	2016-09-29 07:25:00.679229332 +0000
                 +++ /tmp/chef-rendered-template20160929-12541-163si2d	2016-09-29 07:25:00.680229832 +0000
                 @@ -1 +1,17 @@
                 +[Unit]
                 +Description=selenium_node
                 +After=syslog.target network.target
                 +
                 +[Service]
                 +Type=simple
                 +User=selenium
                 +
                 +Environment=DISPLAY=:0
                 +ExecStart=/usr/bin/java -jar "/opt/selenium/server/selenium-server-standalone.jar" -role node -nodeConfig "/opt/selenium/config/selenium_node.json"
                 +KillMode=process
                 +Restart=on-failure
                 +RestartSec=45s
                 +
                 +[Install]
                 +WantedBy=multi-user.target
                 - change mode from '' to '0755'
                 - restore selinux security context
               * service[selenium_node] action enable
                 - enable service service[selenium_node]
               * service[selenium_node] action start
                 - start service service[selenium_node]
               * service[selenium_node] action restart
                 - restart service service[selenium_node]
    
           Recipe: xvfb::service
             * service[xvfb] action restart
               - restart service service[xvfb]
    
           Running handlers:
           Running handlers complete
           Chef Client finished, 45/51 resources updated in 363.478481596 seconds
           Finished converging <default-centos-71> (7m14.87s).
    -----> Setting up <default-centos-71>...
           Finished setting up <default-centos-71> (0m0.00s).
    -----> Verifying <default-centos-71>...
           Preparing files for transfer
    -----> Installing Busser (busser)

I guess the other alternative is fine, however it requires separate configuration which you presumable already have in your `client.rb` file. And no, port should not be an issue because in the client.rb you normally specify like this:

    http_proxy "http://10.1.1.1:1234"
    https_proxy "http://10.1.1.1:1234"

so you have the port included. Also in `client.rb` you have options to specifry username and password, whereas in the other approach you need to add even more parameters. (I haven't checked with username/password, but presumably that works).

**Comment by dhoer** [comment]
Windows is having the following issue:
```
[2016-09-29T16:00:00+00:00] ERROR: SSL Validation failure connecting to host: chromedriver.storage.googleapis.com - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Is there a way to disable the ssl check like the previous version did?

**Comment by dhoer** [comment]
Or do this:
```ruby
# ENV['http_proxy'] = 'http://myself:Password1@proxy.example.org:8080'
proxy = ENV['https_proxy'] || ENV['http_proxy'] || false
no_proxy = ENV['no_proxy'] || false
if proxy && !(no_proxy && proxy.host.include?(no_proxy))
  p_addr = URI(proxy).host if proxy
  p_port = URI(proxy).port if proxy

  userinfo = URI(proxy).userinfo if proxy
  p_user = userinfo.split(':')[0] unless userinfo.nil?
  p_pass = userinfo.split(':')[1] unless userinfo.nil?

  response = Net::HTTP.new(uri.host, nil, p_addr, p_port, p_user, p_pass).start { |http| http.get uri.request_uri }
else
  response = Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }
end
```
This would be consistent with how chef client handles proxies.

**Comment by aukevanleeuwen** [comment]
Is that a real-world example of the windows version failing? Or is that a test setup somewhere? It seems to me that the `remote_file 'download chromedriver'` that actually downloads the chrome driver binary would also fail on a SSL failure in that case right?

**Comment by aukevanleeuwen** [comment]
$ knife ssl check https://chromedriver.storage.googleapis.com                                                                                                        
    Connecting to host chromedriver.storage.googleapis.com:443
    Successfully verified certificates from `chromedriver.storage.googleapis.com'

**Comment by dhoer** [comment]
This is appveyor's 2012r2 image.  This is usually an issue with ssl certs in ruby http being out of date.  Windows version of chef must be a little different than linux. That is why I ignore the certs, which is probably a bad thing to do, but hey, it works!

**Comment by sspans** [comment]
Perhaps it would be best to limit that to specific windows versions in that case.

**Comment by dhoer** [comment]
@sspans: @aukevanleeuwen was able to get around this be setting the following in chefspec:
`Chef::Config[:ssl_verify_mode] = :verify_none`

**Pull request merged**
